#!/usr/bin/env python
import freenect
import matplotlib.pyplot as mp
import numpy
import frame_convert
import signal
from multiprocessing import Process, Value
import time
import BaseHTTPServer
import json

keep_running = True


def get_depth():
    depth = frame_convert.pretty_depth(freenect.sync_get_depth()[0])
    #min = depth.argmin()
    #where = numpy.where(depth == min, True, False)
    #count = numpy.count_nonzero(where == True)
    #print min, count
    min = depth.argmin()
    minloc = numpy.unravel_index(min, depth.shape)
    y = float(minloc[0])/float(depth.shape[0])
    x = float(minloc[1])/float(depth.shape[1])
    return depth, x, y, min


def handler(signum, frame):
    """Sets up the kill handler, catches SIGINT"""
    global keep_running
    keep_running = False


def http_handler_factory(sh_x, sh_y, sh_min):
    class HTTPHandler(BaseHTTPServer.BaseHTTPRequestHandler):
        def do_GET(self):
            self.send_response(200)
            self.send_header("content-type", "application/json")
            self.end_headers()

            self.wfile.write(json.dumps({
                'x': sh_x.value,
                'y': sh_y.value,
                'min': sh_min.value,
            }))

    return HTTPHandler


def consumer(sh_x, sh_y, sh_min):
    server_address=('0.0.0.0', 8888)
    handler = http_handler_factory(sh_x, sh_y, sh_min)
    httpd = BaseHTTPServer.HTTPServer(server_address, handler)
    while True:
        httpd.handle_request()
        print sh_x.value, sh_y.value, sh_min.value


mp.ion()
mp.gray()
mp.figure(1)
image_depth = mp.imshow(get_depth()[0], interpolation='nearest', animated=True)
print('Press Ctrl-C in terminal to stop')
signal.signal(signal.SIGINT, handler)

sh_x = Value('d', 0.0)
sh_y = Value('d', 0.0)
sh_min = Value('d', 0.0)

p = Process(target=consumer, args=(sh_x, sh_y, sh_min))
p.start()

while keep_running:
    mp.figure(1)
    depth, x, y, min = get_depth()
    image_depth.set_data(depth)
    sh_x.value = x
    sh_y.value = y
    sh_min.value = min
    mp.draw()
    mp.waitforbuttonpress(0.01)
